# code: language=ansible
---
galaxy_info:
  author: "Anatoliy Kopylov"
  description: "Part of home-lab-ca bundle. Certificate signing automation."
  min_ansible_version: "2.14.3"
  license: BSD
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy